spring.application.name=torneo

# Configuracion de SQLite
spring.datasource.url=jdbc:sqlite:pingpong.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Puerto del servidor
server.port=8080
